#!/bin/sh

source $(dirname $0)/_common

stop_if_not_get

delay=$(tc qdisc ls dev eth0 | grep qdisc | cut -d " " -f 10)

#echo "Content-Type: text/plain"
#echo

if [ "$delay" = "100.0ms" ]; then
  echo "3g"
elif [ "$delay" = "400.0ms" ]; then
  echo "dsl"
elif [ "$delay" = "800.0ms" ]; then
  echo "edge"
elif [ "$delay" = "1.5s" ]; then
  echo "bad"
elif [ "$delay" = "3.0s" ]; then
  echo "very_bad"
else
  echo "none"
fi

